apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: your-dockerhub-username/laravel-app:latest
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_KEY
              value: "your-laravel-app-key"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_DATABASE
              value: "your-db-name"
            - name: DB_USERNAME
              value: "your-db-user"
            - name: DB_PASSWORD
              value: "your-db-password"
