apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: your-dockerhub-username/laravel-app:latest
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_KEY
              value: "base64:h8KQqAGPjWgdcRvCvZEnDwh6ZUbfjF88FJJn+uZs6/w="
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_DATABASE
              value: "my_app_2"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "magynevy@11055"
